{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.freewheel",
    "module": "admanager",
    "version": "7.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "admanager-7.12.0.aar",
          "url": "admanager-7.12.0.aar",
          "size": 724833,
          "sha512": "6f6d188e8863ad8c4164a0c1039b6691efccf9c142656c707aa2ac6e284fd30865c9c77dc29828fb42d76e30396e95849c1b74f6725c1ce1ebb99253a2839129",
          "sha256": "1f31503bd0a46ae34b3c1f798728b6d5eb29bfd8caf45a287e252dff1f10797f",
          "sha1": "86dba53641eed2871ba543a655f00081a5213f99",
          "md5": "ba8fbeb271a59b99c1afa3f0fe77d01f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "admanager-7.12.0.aar",
          "url": "admanager-7.12.0.aar",
          "size": 724833,
          "sha512": "6f6d188e8863ad8c4164a0c1039b6691efccf9c142656c707aa2ac6e284fd30865c9c77dc29828fb42d76e30396e95849c1b74f6725c1ce1ebb99253a2839129",
          "sha256": "1f31503bd0a46ae34b3c1f798728b6d5eb29bfd8caf45a287e252dff1f10797f",
          "sha1": "86dba53641eed2871ba543a655f00081a5213f99",
          "md5": "ba8fbeb271a59b99c1afa3f0fe77d01f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "admanager-7.12.0-sources.jar",
          "url": "admanager-7.12.0-sources.jar",
          "size": 763861,
          "sha512": "6611cc40392d8af4a6c6ee940f2a3bc8aea2b3ea82eead678a131fc16cd849e2aa76252b5a34d353e8da82e59d05efad842d7f225bd0a404eb9829353b34f8e3",
          "sha256": "528650c9d635e937f6e1370c7c832d87b2ee3af77c66a450a0f032c431b129a7",
          "sha1": "cb202bb8e49a775408530e994cd4109229c669d2",
          "md5": "054c15a6e7e4e70b1c7a6f63c9e05975"
        }
      ]
    }
  ]
}
